.Dd $Mdocdate$
.Dt goiv 1
.Os goiv 1.0
.Sh NAME
.Nm goiv
.Nd go image viewer 1.0
.Sh SYNOPSIS
.Nm
.Bk -words
.Op Fl h
.Ek
.Nm
.Bk -words
.Op Fl r
.Ar path
.Op Ar paths ...
.Sh DESCRIPTION
.Nm
sequentially displays images from some paths, scanned recursively when
relevant. The final list of images is eventually shuffled.
.Pp
The GUI is sharp, and relies on a a bunch of (undocumented) shortcuts.